test:
  stage: build
  script:
    - node --version
    - npm install
    - npm test
  image: node:14.16.0-alpine3.10
  tags:
    - mss
    - docker

deploy-prod:
  stage: deploy
  image: google/cloud-sdk:330.0.0
  script:
    - echo "Deploying to GAE"
    - echo "$GAE_KEYFILE" > "$(pwd)/gae_keyfile.json"
    - gcloud auth activate-service-account mss-sample-service@appspot.gserviceaccount.com --key-file "$(pwd)/gae_keyfile.json"
    - gcloud config set project mss-sample-service
    - gcloud app deploy -q
  tags:
    - mss
    - docker
