# Controls when the workflow will run
on:
  # Triggers the workflow on push on all branches
  push:
    branches:
      - '**'

name: Build and Test

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm install
      - run: npm test
